version: '2'

services:
  app:
    image: '${IMAGE_NAME}'
    container_name: moviedatabase-api
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq

    env_file:
      - .env

  rabbitmq:
    image: 'rabbitmq:3-management-alpine'
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672