name: Trigger auto deployment for containerapp serverless-movie-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/serverless-movie-backend-AutoDeployTrigger-01b60dc5-757a-4d1b-aa55-f6fbd7350a8b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: bisoft15container.azurecr.io
          username: ${{ secrets.SERVERLESSMOVIEBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.SERVERLESSMOVIEBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bisoft15container.azurecr.io/serverless-movie-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVERLESSMOVIEBACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n serverless-movie-backend -g serverless-backend --server bisoft15container.azurecr.io --username  ${{ secrets.SERVERLESSMOVIEBACKEND_REGISTRY_USERNAME }} --password ${{ secrets.SERVERLESSMOVIEBACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n serverless-movie-backend -g serverless-backend --image bisoft15container.azurecr.io/serverless-movie-backend:${{ github.sha }}
